# Function to do PreProcessing


In [1]:
from nltk.stem.snowball import ItalianStemmer
from nltk import RegexpTokenizer
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [2]:
stopwords = nltk.corpus.stopwords.words("italian")
def process_text(text):
  to_return = [ItalianStemmer().stem(x) for x in RegexpTokenizer(r"\w+").tokenize(text) if not x in stopwords]
  #return (" ".join(to_return))
  return to_return

In [3]:
process_text('La Connessione di Nina fa schifo.')

['la', 'connession', 'nin', 'fa', 'schif']

In [4]:
import pandas as pd

#Wiki Pages data

In [ ]:
wikineutral = pd.read_csv('/content/drive/My Drive/Topic detection/wiki_topics.csv', index_col = 0 , sep = "\t", encoding = "utf-8")

In [ ]:
wikineutral.shape

(354, 2)

In [ ]:
wikineutral.drop(wikineutral.tail(200).index, inplace = True)

In [ ]:
wikineutral.shape

(154, 2)

In [ ]:
wikineutral.shape

(154, 2)

In [ ]:
wikineutral.head()

Topic                                               Text
0  Arte e cultura  Coordinate: 45°22′02.71″N 10°13′15.84″E / 45...
1  Arte e cultura  Coordinate: 43°34′38.28″N 11°14′51″E / 43.57...
2  Arte e cultura  Voci principali: Architettura del Settecento, ...
3  Arte e cultura  Coordinate: 45°26′24.29″N 10°59′19.71″E / 45...
4  Arte e cultura  Coordinate: 45°26′20″N 10°59′40″E / 45.43888...

In [ ]:
wikineutral.drop(['Topic'], axis = 1,  inplace = True)
wikineutral['Sentiment'] = 'neutral'

wikineutral.to_csv('/content/drive/My Drive/Topic detection/Wikineutral.csv')

In [5]:
wikineutral = pd.read_csv('/content/drive/My Drive/Topic detection/Wikineutral.csv', index_col = 0)
wikineutral.head()

Text Sentiment
0  Coordinate: 45°22′02.71″N 10°13′15.84″E / 45...   neutral
1  Coordinate: 43°34′38.28″N 11°14′51″E / 43.57...   neutral
2  Voci principali: Architettura del Settecento, ...   neutral
3  Coordinate: 45°26′24.29″N 10°59′19.71″E / 45...   neutral
4  Coordinate: 45°26′20″N 10°59′40″E / 45.43888...   neutral

# Amazon Data and processing of their sentiment

In [10]:
Amazonrewiews = pd.read_csv('/content/drive/My Drive/Topic detection/TrainDataSentiment.csv', index_col = 0 )
Amazonrewiews.head()

content  rating
0  Ho acquistato questa confezione di mascherine ...       4
1  Attenzione, ha un ferretto nasale in plastica ...       1
2  La confezione di cartone era già aperta, appen...       1
3  Mascherine vendute come "Maschera Chirurgica 3...       1
4                   ARRIVATO APERTO PESSIMO PRODOTTO       1

In [11]:
Amazonrewiews['rating'] = Amazonrewiews['rating'].map({5: 'positive', 4: 'positive', 1:'negative', 2:'negative',3:'negative' })
Ama = Amazonrewiews.rename(columns={'content': 'Text', 'rating': 'Sentiment' })
Ama.head()


Text Sentiment
0  Ho acquistato questa confezione di mascherine ...  positive
1  Attenzione, ha un ferretto nasale in plastica ...  negative
2  La confezione di cartone era già aperta, appen...  negative
3  Mascherine vendute come "Maschera Chirurgica 3...  negative
4                   ARRIVATO APERTO PESSIMO PRODOTTO  negative

In [12]:
Ama.to_csv('/content/drive/My Drive/Topic detection/AmaSentimented.csv')
Ama = pd.read_csv('/content/drive/My Drive/Topic detection/AmaSentimented.csv', index_col =0)
Ama.head()

Text Sentiment
0  Ho acquistato questa confezione di mascherine ...  positive
1  Attenzione, ha un ferretto nasale in plastica ...  negative
2  La confezione di cartone era già aperta, appen...  negative
3  Mascherine vendute come "Maschera Chirurgica 3...  negative
4                   ARRIVATO APERTO PESSIMO PRODOTTO  negative

In [13]:
Ama['Sentiment'][0]

'positive'

In [14]:
wikineutral['Sentiment'][0]

'neutral'

In [15]:
wikineutral.head()

Text Sentiment
0  Coordinate: 45°22′02.71″N 10°13′15.84″E / 45...   neutral
1  Coordinate: 43°34′38.28″N 11°14′51″E / 43.57...   neutral
2  Voci principali: Architettura del Settecento, ...   neutral
3  Coordinate: 45°26′24.29″N 10°59′19.71″E / 45...   neutral
4  Coordinate: 45°26′20″N 10°59′40″E / 45.43888...   neutral

In [ ]:
Ama.shape

(460, 2)

In [22]:
wikineutral.shape

(154, 2)

# Reddit Data

In [21]:
reddit_data1 = pd.read_csv("/content/drive/My Drive/Topic detection/AMANOREDDIT.csv", index_col = 0).dropna()[["Text", "Sentiment"]]
reddit_data = reddit_data1.drop_duplicates()
reddit_data.head()

Text Sentiment
0  Chiudo il thread, andate su quello nuovo\n\n/r...   neutral
1  >Ore 19.30 - Il presunto «paziente 0» negativo...  negative
2  > Si allontana da Codogno e torna ad Avellino:...   neutral
3  Dogana slovenia/croazia. Il poliziotto croato ...  negative
4  ho dato una veloce occhiata sui social \n\nNor...  negative

In [27]:
reddit_data.shape

(587, 2)

# Merge the data into a unique dataset

In [25]:
TrainData = pd.concat([Ama, wikineutral], ignore_index = True)
TrainData = pd.concat([TrainData, reddit_data], ignore_index = True)

In [28]:
TrainData.head()

Text Sentiment
0  Ho acquistato questa confezione di mascherine ...  positive
1  Attenzione, ha un ferretto nasale in plastica ...  negative
2  La confezione di cartone era già aperta, appen...  negative
3  Mascherine vendute come "Maschera Chirurgica 3...  negative
4                   ARRIVATO APERTO PESSIMO PRODOTTO  negative

In [29]:
TrainData.shape

(1201, 2)

In [30]:
TrainData.to_csv('/content/drive/My Drive/Topic detection/TrainData3DB.csv')

In [31]:
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/TrainData3DB.csv', index_col = 0 )
TrainData.head()

Text Sentiment
0  Ho acquistato questa confezione di mascherine ...  positive
1  Attenzione, ha un ferretto nasale in plastica ...  negative
2  La confezione di cartone era già aperta, appen...  negative
3  Mascherine vendute come "Maschera Chirurgica 3...  negative
4                   ARRIVATO APERTO PESSIMO PRODOTTO  negative

#Process the texts in TrainData and adding col 'Processed Text'

In [32]:
TrainData = TrainData.dropna()
tokenized_data = []
from tqdm import tqdm 
for index in tqdm(range(len(TrainData))):
  tokenized_data.append(" ".join(process_text(TrainData.iloc[index]["Text"])))

100%|██████████| 1200/1200 [00:20<00:00, 57.24it/s]


In [33]:
TrainData["Processed Text"] = tokenized_data

In [34]:
TrainData.head()

Text  ...                                     Processed Text
0  Ho acquistato questa confezione di mascherine ...  ...  ho acquist confezion mascherin 19 99 quind 40 ...
1  Attenzione, ha un ferretto nasale in plastica ...  ...  attenzion ferrett nasal plastic permett far ad...
2  La confezione di cartone era già aperta, appen...  ...  la confezion carton già apert appen pres lat t...
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  mascherin vend mascher chirurg 3p tip iir conf...
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...                         arriv apert pessim prodott

[5 rows x 3 columns]

In [35]:
TrainData.to_csv('/content/drive/My Drive/Topic detection/ProcessedTrainData3DB.csv')


## Creation tftidf model from Processed Text

---



In [57]:
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/ProcessedTrainData3DB.csv', index_col = 0 )
TrainData.dropna(inplace = True)

In [58]:
TrainData.head()

Text  ...                                     Processed Text
0  Ho acquistato questa confezione di mascherine ...  ...  ho acquist confezion mascherin 19 99 quind 40 ...
1  Attenzione, ha un ferretto nasale in plastica ...  ...  attenzion ferrett nasal plastic permett far ad...
2  La confezione di cartone era già aperta, appen...  ...  la confezion carton già apert appen pres lat t...
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  mascherin vend mascher chirurg 3p tip iir conf...
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...                         arriv apert pessim prodott

[5 rows x 3 columns]

In [59]:
TrainList = TrainData['Processed Text'].tolist()

In [60]:
TrainList[0]

'ho acquist confezion mascherin 19 99 quind 40 centesim mascherin prezz somm onest la qualit mascherin avvis discret prov altre consistt indubb maggior risult tatt morbid spess nell confezion present certific cines attest tipolog iir gli elast manteng molt ben già utilizz 5 senz nessun problem ven difett essenzial due 1 mascherin chius scatol senz imball isol nessun plastic protezion 2 ferrett string nas sembr esser metall quind pieg ben senz raggiung chiusur massim'

In [61]:
TrainData['Processed Text'].isnull().values.any()

False

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(TrainList)
X #Matrix with each row TfIdf

<1198x38878 sparse matrix of type '<class 'numpy.float64'>'
	with 279581 stored elements in Compressed Sparse Row format>

# Processing the text and performing SVD with 100-200-300 components


In [63]:
import joblib
joblib.dump( vectorizer, '/content/drive/My Drive/Topic detection/Vectorizer.pkl')

vectorizer_loaded = joblib.load('/content/drive/My Drive/Topic detection/Vectorizer.pkl')

In [64]:
# SVD in 100/200/300 components

In [65]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import random as sparse_random
from sklearn.random_projection import sparse_random_matrix
import joblib
comps = [100, 200, 300]
def Svd(comps):
  SVDMatrices = []
  for i in comps:
    svd = TruncatedSVD(n_components=i, n_iter=7, random_state=42)
    a = svd.fit_transform(X)
    SVDMatrices.append(a)
    joblib.dump( svd, '/content/drive/My Drive/Topic detection/SVD'+str(i)+'.pkl')
    print(comps, svd.explained_variance_ratio_.sum())
  return (SVDMatrices)
#print(svd.explained_variance_ratio_)



#print(svd.singular_values_) A = USV^t S singular matrix (x0000000
                                                      #      0y00000000000000000)


In [66]:
SVDMatrices = Svd(comps)

[100, 200, 300] 0.3858069663463686
[100, 200, 300] 0.5511866267659707
[100, 200, 300] 0.6638118360370318


In [67]:
#len(SVDMatrices[0][0][612])
len(SVDMatrices[0])

1198

In [68]:
def namescreator(matrices = SVDMatrices, rws = 1198):
  names = []
 # print(len(names))
  for j in range(0,len(matrices)):
      names.append([])
  for i in range(len(matrices)):
   #   print(i)
     # print(len(matrices[i]))
      ln = len(matrices[i][0])
     # print(ln)
     # print(names)
      temp = []
      for j in range(0,len(matrices[i][0])):
         temp.append([])
      print(len(temp))
      for position in range(len(matrices[i][0])):
       # print(position)
        for row in range(rws):
       #  print(a[position][col])
        # print(range(ln-1))
         temp[position].append(matrices[i][row][position])
      for k in temp:
       names[i].append(k)

  return names
#print(len(a[0]))

In [69]:
ttry = namescreator([SVDMatrices[1]])
len(ttry[0])

200


200

In [70]:
len(ttry)

1

In [72]:
l = []
#names of columns for svd dataframes
for i in range(3):
  l.append([])
for i in range(1,101):
    l[0].append('feat'+str(i))
for i in range(1,201):
    l[1].append('feat'+str(i))
for i in range(1,301):
    l[2].append('feat'+str(i))

In [73]:
len(l[2])

300

In [74]:
#I have a list with 3 components and in every one 100/200/300 columns
#I have a set of names
df100 = TrainData.copy()
df200 = TrainData.copy()
df300 = TrainData.copy()

In [75]:
def datafinal(l, a2, df):
  j = 0
  for i in l:
  #  print(len(a2[j]))
    df[i]= a2[j]
    j = j+1
  return df

In [76]:
df300.head()

Text  ...                                     Processed Text
0  Ho acquistato questa confezione di mascherine ...  ...  ho acquist confezion mascherin 19 99 quind 40 ...
1  Attenzione, ha un ferretto nasale in plastica ...  ...  attenzion ferrett nasal plastic permett far ad...
2  La confezione di cartone era già aperta, appen...  ...  la confezion carton già apert appen pres lat t...
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  mascherin vend mascher chirurg 3p tip iir conf...
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...                         arriv apert pessim prodott

[5 rows x 3 columns]

# We have 3 df in respect at the different svd!


In [77]:
df100 = datafinal(l[0], namescreator([SVDMatrices[0]])[0], df100 )
df200 = datafinal(l[1], namescreator([SVDMatrices[1]])[0], df200 )
df300 = datafinal(l[2], namescreator([SVDMatrices[2]])[0], df300 )

df100.to_csv('/content/drive/My Drive/Topic detection/Df100.csv')
df200.to_csv('/content/drive/My Drive/Topic detection/Df200.csv')
df300.to_csv('/content/drive/My Drive/Topic detection/Df300.csv')
df100.head()


100
200
300


Text  ...   feat100
0  Ho acquistato questa confezione di mascherine ...  ... -0.107973
1  Attenzione, ha un ferretto nasale in plastica ...  ...  0.136631
2  La confezione di cartone era già aperta, appen...  ...  0.003170
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  0.005090
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...  0.033338

[5 rows x 103 columns]

In [ ]:
len(df300.columns)

303

In [ ]:
df100.head()

Text  ...                                     Processed Text
0  Ho acquistato questa confezione di mascherine ...  ...  ho acquist confezion mascherin 19 99 quind 40 ...
1  Attenzione, ha un ferretto nasale in plastica ...  ...  attenzion ferrett nasal plastic permett far ad...
2  La confezione di cartone era già aperta, appen...  ...  la confezion carton già apert appen pres lat t...
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  mascherin vend mascher chirurg 3p tip iir conf...
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...                         arriv apert pessim prodott

[5 rows x 3 columns]

In [ ]:
len(l[0])
len(namescreator([SVDMatrices[0]])[0])

100


100

## SVM LAST STEP

#Df100 Tested on SVM


In [ ]:
df100.head()

Text  ...   feat100
0  Ho acquistato questa confezione di mascherine ...  ...  0.097730
1  Attenzione, ha un ferretto nasale in plastica ...  ... -0.142211
2  La confezione di cartone era già aperta, appen...  ...  0.043726
3  Mascherine vendute come "Maschera Chirurgica 3...  ... -0.051969
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ... -0.002274

[5 rows x 103 columns]

In [78]:
import pandas as pd
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/Df100.csv', index_col = 0 )
TrainData.head()

Text  ...   feat100
0  Ho acquistato questa confezione di mascherine ...  ... -0.107973
1  Attenzione, ha un ferretto nasale in plastica ...  ...  0.136631
2  La confezione di cartone era già aperta, appen...  ...  0.003170
3  Mascherine vendute come "Maschera Chirurgica 3...  ...  0.005090
4                   ARRIVATO APERTO PESSIMO PRODOTTO  ...  0.033338

[5 rows x 103 columns]

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
X_train2, X_test2, y_train2, y_test2 = train_test_split( TrainData.drop(['Text', 'Sentiment', 'Processed Text'], axis = 1),
TrainData['Sentiment'], test_size=0.3, random_state=42)

In [82]:
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

# encoding train labels 
encoder.fit(y_train2)
Y_train2 = encoder.transform(y_train2)

encoder = preprocessing.LabelEncoder()

# encoding y_test2 labels 
encoder.fit(y_test2)
Y_test2 = encoder.transform(y_test2)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled2 = scaler.fit_transform(X_train2)

scaler = StandardScaler()
X_test_scaled2 = scaler.fit_transform(X_test2)


In [83]:
Y_test2

array([0, 1, 2, 0, 2, 1, 0, 0, 2, 0, 2, 2, 2, 1, 0, 0, 1, 1, 0, 0, 2, 1,
       1, 2, 2, 2, 1, 1, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 0, 1, 2, 0, 1, 2,
       2, 2, 2, 0, 2, 0, 1, 0, 0, 0, 0, 2, 0, 1, 1, 0, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 0, 0, 1, 0, 2, 2, 0, 2, 1, 0, 0, 2, 1, 0, 1, 0, 1, 2,
       2, 1, 1, 1, 2, 2, 2, 2, 1, 0, 2, 0, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0,
       2, 1, 0, 1, 0, 1, 2, 2, 1, 0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 0, 2, 1,
       0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 1, 1, 2, 1, 0, 0, 0, 0, 1,
       0, 1, 2, 1, 2, 0, 2, 1, 2, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 2, 2, 1,
       2, 2, 1, 0, 2, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 2, 0, 2, 1, 1,
       2, 0, 0, 1, 2, 1, 1, 2, 0, 2, 2, 2, 2, 1, 2, 2, 0, 1, 1, 0, 2, 0,
       2, 1, 0, 1, 2, 2, 2, 0, 1, 0, 2, 2, 0, 2, 0, 1, 0, 0, 1, 2, 0, 0,
       0, 2, 1, 1, 1, 1, 1, 1, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 2, 2, 0, 0, 1, 2, 0, 1, 0, 1, 2, 1,

In [86]:
params_grid = [{'kernel': ['rbf', 'poly', 'sigmoid'], 'gamma': [5e-3, 3e-4, 1e-5],
                     'C': [10, 20, 5, 200]} ]

In [87]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate

svm_model = GridSearchCV(SVC(), params_grid, cv=5,  n_jobs = 12, verbose = 12)
svm_model.fit(X_train_scaled2, y_train2)

Fitting 5 folds for each of 36 candidates, totalling 180 fits


[Parallel(n_jobs=12)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done   1 tasks      | elapsed:    4.2s
[Parallel(n_jobs=12)]: Done   2 tasks      | elapsed:    4.6s
[Parallel(n_jobs=12)]: Done   3 tasks      | elapsed:    4.6s
[Parallel(n_jobs=12)]: Done   4 tasks      | elapsed:    4.6s
[Parallel(n_jobs=12)]: Done   5 tasks      | elapsed:    4.8s
[Parallel(n_jobs=12)]: Done   6 tasks      | elapsed:    5.3s
[Parallel(n_jobs=12)]: Done   7 tasks      | elapsed:    5.5s
[Parallel(n_jobs=12)]: Done   8 tasks      | elapsed:    5.6s
[Parallel(n_jobs=12)]: Done   9 tasks      | elapsed:    5.7s
[Parallel(n_jobs=12)]: Done  10 tasks      | elapsed:    5.9s
[Parallel(n_jobs=12)]: Done  11 tasks      | elapsed:    6.0s
[Parallel(n_jobs=12)]: Done  12 tasks      | elapsed:    6.3s
[Parallel(n_jobs=12)]: Done  13 tasks      | elapsed:    6.3s
[Parallel(n_jobs=12)]: Done  14 tasks      | elapsed:    6.5s
[Parallel(n_jobs=12)]: Done  15 tasks      | elapsed:  

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=12,
             param_grid=[{'C': [10, 20, 5, 200],
                          'gamma': [0.005, 0.0003, 1e-05],
                          'kernel': ['rbf', 'poly', 'sigmoid']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=12)

In [88]:
svm_model.best_params_

{'C': 200, 'gamma': 0.0003, 'kernel': 'rbf'}

In [89]:
final_model = svm_model.best_estimator_
final_model

SVC(C=200, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0003, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [90]:
Y_pred = final_model.predict(X_test_scaled2)
#Y_pred_label = list(encoder.inverse_transform(Y_pred))
#Y_pred is cathegorical

print(confusion_matrix(y_test2,Y_pred))
print("\n")
print(classification_report(y_test2,Y_pred))

print("Training set score for SVM: %f" % final_model.score(X_train_scaled2 , y_train2))
print("Testing  set score for SVM: %f" % final_model.score(X_test_scaled2  , y_test2 ))

svm_model.score

[[89 29 12]
 [17 89  4]
 [29 26 65]]


              precision    recall  f1-score   support

    negative       0.66      0.68      0.67       130
     neutral       0.62      0.81      0.70       110
    positive       0.80      0.54      0.65       120

    accuracy                           0.68       360
   macro avg       0.69      0.68      0.67       360
weighted avg       0.69      0.68      0.67       360

Training set score for SVM: 0.847255
Testing  set score for SVM: 0.675000


<bound method BaseSearchCV.score of GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=12,
             param_grid=[{'C': [10, 20, 5, 200],
                          'gamma': [0.005, 0.0003, 1e-05],
                          'kernel': ['rbf', 'poly', 'sigmoid']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=12)>

In [91]:
#how to save a model
import joblib
joblib.dump( final_model, '/content/drive/My Drive/Topic detection/SVM100.pkl')

my_model_loaded = joblib.load('/content/drive/My Drive/Topic detection/SVM100.pkl')

# Df200

In [92]:
import pandas as pd
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/Df200.csv', index_col = 0 )
TrainData.head()

X_train2, X_test2, y_train2, y_test2 = train_test_split( TrainData.drop(['Text', 'Sentiment', 'Processed Text'], axis = 1),
TrainData['Sentiment'], test_size=0.3, random_state=42)

from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

# encoding train labels 
encoder.fit(y_train2)
Y_train2 = encoder.transform(y_train2)

encoder = preprocessing.LabelEncoder()

# encoding y_test2 labels 
encoder.fit(y_test2)
Y_test2 = encoder.transform(y_test2)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled2 = scaler.fit_transform(X_train2)

scaler = StandardScaler()
X_test_scaled2 = scaler.fit_transform(X_test2)

params_grid = [{'kernel': ['rbf', 'poly', 'sigmoid'], 'gamma': [5e-3, 3e-4, 1e-5],
                     'C': [10, 20, 5, 200]} ]


from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate

svm_model = GridSearchCV(SVC(), params_grid, cv=5,  n_jobs = 12, verbose = 12)
svm_model.fit(X_train_scaled2, y_train2)


final_model = svm_model.best_estimator_
final_model

Y_pred = final_model.predict(X_test_scaled2)
#Y_pred_label = list(encoder.inverse_transform(Y_pred))
#Y_pred is cathegorical

print(confusion_matrix(y_test2,Y_pred))
print("\n")
print(classification_report(y_test2,Y_pred))

print("Training set score for SVM: %f" % final_model.score(X_train_scaled2 , y_train2))
print("Testing  set score for SVM: %f" % final_model.score(X_test_scaled2  , y_test2 ))

print(svm_model.score)

#how to save a model
import joblib
joblib.dump( final_model, '/content/drive/My Drive/Topic detection/SVM200.pkl')

#my_model_loaded = joblib.load('/content/drive/My Drive/Topic detection/SVM200.pkl')

Fitting 5 folds for each of 36 candidates, totalling 180 fits


[Parallel(n_jobs=12)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done   1 tasks      | elapsed:    0.9s
[Parallel(n_jobs=12)]: Done   2 tasks      | elapsed:    1.1s
[Parallel(n_jobs=12)]: Done   3 tasks      | elapsed:    1.1s
[Parallel(n_jobs=12)]: Done   4 tasks      | elapsed:    1.1s
[Parallel(n_jobs=12)]: Done   5 tasks      | elapsed:    1.1s
[Parallel(n_jobs=12)]: Done   6 tasks      | elapsed:    1.1s
[Parallel(n_jobs=12)]: Done   7 tasks      | elapsed:    1.1s
[Parallel(n_jobs=12)]: Done   8 tasks      | elapsed:    1.2s
[Parallel(n_jobs=12)]: Done   9 tasks      | elapsed:    1.9s
[Parallel(n_jobs=12)]: Done  10 tasks      | elapsed:    2.0s
[Parallel(n_jobs=12)]: Done  11 tasks      | elapsed:    2.1s
[Parallel(n_jobs=12)]: Done  12 tasks      | elapsed:    2.3s
[Parallel(n_jobs=12)]: Done  13 tasks      | elapsed:    2.3s
[Parallel(n_jobs=12)]: Done  14 tasks      | elapsed:    2.3s
[Parallel(n_jobs=12)]: Done  15 tasks      | elapsed:  

[[91 33  6]
 [20 86  4]
 [27 26 67]]


              precision    recall  f1-score   support

    negative       0.66      0.70      0.68       130
     neutral       0.59      0.78      0.67       110
    positive       0.87      0.56      0.68       120

    accuracy                           0.68       360
   macro avg       0.71      0.68      0.68       360
weighted avg       0.71      0.68      0.68       360

Training set score for SVM: 0.821002
Testing  set score for SVM: 0.677778
<bound method BaseSearchCV.score of GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs

['/content/drive/My Drive/Topic detection/SVM200.pkl']

# Df300

In [93]:
import pandas as pd
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/Df300.csv', index_col = 0 )
TrainData.head()

X_train2, X_test2, y_train2, y_test2 = train_test_split( TrainData.drop(['Text', 'Sentiment', 'Processed Text'], axis = 1),
TrainData['Sentiment'], test_size=0.3, random_state=42)

from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

# encoding train labels 
encoder.fit(y_train2)
Y_train2 = encoder.transform(y_train2)

encoder = preprocessing.LabelEncoder()

# encoding y_test2 labels 
encoder.fit(y_test2)
Y_test2 = encoder.transform(y_test2)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled2 = scaler.fit_transform(X_train2)

scaler = StandardScaler()
X_test_scaled2 = scaler.fit_transform(X_test2)

params_grid = [{'kernel': ['rbf', 'poly', 'sigmoid'], 'gamma': [5e-3, 3e-4, 1e-5],
                     'C': [10, 20, 5, 200]} ]


from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate

svm_model = GridSearchCV(SVC(), params_grid, cv=5,  n_jobs = 12, verbose = 12)
svm_model.fit(X_train_scaled2, y_train2)


final_model = svm_model.best_estimator_
final_model

Y_pred = final_model.predict(X_test_scaled2)
#Y_pred_label = list(encoder.inverse_transform(Y_pred))
#Y_pred is cathegorical

print(confusion_matrix(y_test2,Y_pred))
print("\n")
print(classification_report(y_test2,Y_pred))

print("Training set score for SVM: %f" % final_model.score(X_train_scaled2 , y_train2))
print("Testing  set score for SVM: %f" % final_model.score(X_test_scaled2  , y_test2 ))

print(svm_model.score)

#how to save a model
import joblib
joblib.dump( final_model, '/content/drive/My Drive/Topic detection/SVM300.pkl')

#my_model_loaded = joblib.load('/content/drive/My Drive/Topic detection/SVM200.pkl')

Fitting 5 folds for each of 36 candidates, totalling 180 fits


[Parallel(n_jobs=12)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done   1 tasks      | elapsed:    0.8s
[Parallel(n_jobs=12)]: Done   2 tasks      | elapsed:    0.8s
[Parallel(n_jobs=12)]: Done   3 tasks      | elapsed:    0.9s
[Parallel(n_jobs=12)]: Done   4 tasks      | elapsed:    1.0s
[Parallel(n_jobs=12)]: Done   5 tasks      | elapsed:    1.2s
[Parallel(n_jobs=12)]: Done   6 tasks      | elapsed:    2.4s
[Parallel(n_jobs=12)]: Done   7 tasks      | elapsed:    2.4s
[Parallel(n_jobs=12)]: Done   8 tasks      | elapsed:    2.4s
[Parallel(n_jobs=12)]: Done   9 tasks      | elapsed:    2.4s
[Parallel(n_jobs=12)]: Done  10 tasks      | elapsed:    2.4s
[Parallel(n_jobs=12)]: Done  11 tasks      | elapsed:    2.7s
[Parallel(n_jobs=12)]: Done  12 tasks      | elapsed:    2.8s
[Parallel(n_jobs=12)]: Done  13 tasks      | elapsed:    2.8s
[Parallel(n_jobs=12)]: Done  14 tasks      | elapsed:    2.9s
[Parallel(n_jobs=12)]: Done  15 tasks      | elapsed:  

[[96 25  9]
 [24 77  9]
 [30 23 67]]


              precision    recall  f1-score   support

    negative       0.64      0.74      0.69       130
     neutral       0.62      0.70      0.66       110
    positive       0.79      0.56      0.65       120

    accuracy                           0.67       360
   macro avg       0.68      0.67      0.66       360
weighted avg       0.68      0.67      0.67       360

Training set score for SVM: 0.908115
Testing  set score for SVM: 0.666667
<bound method BaseSearchCV.score of GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs

['/content/drive/My Drive/Topic detection/SVM300.pkl']

In [ ]:
my_model_loaded

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0003, kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

# Bayesian Models (bad af F)


In [94]:
from sklearn.naive_bayes import GaussianNB
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/Df200.csv', index_col = 0 )
TrainData.head()

X_train2, X_test2, y_train2, y_test2 = train_test_split( TrainData.drop(['Text', 'Sentiment', 'Processed Text'], axis = 1),
TrainData['Sentiment'], test_size=0.3, random_state=42)

from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

# encoding train labels 
encoder.fit(y_train2)
Y_train2 = encoder.transform(y_train2)

encoder = preprocessing.LabelEncoder()

# encoding y_test2 labels 
encoder.fit(y_test2)
Y_test2 = encoder.transform(y_test2)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled2 = scaler.fit_transform(X_train2)

scaler = StandardScaler()
X_test_scaled2 = scaler.fit_transform(X_test2)




In [95]:
# Gaussian assumption

gnb = GaussianNB()
Y_pred = gnb.fit(X_train2, y_train2).predict(X_test2)

print(confusion_matrix(y_test2,Y_pred))
print("\n")
print(classification_report(y_test2,Y_pred))

print("Training set score for SVM: %f" % gnb.score(X_train_scaled2 , y_train2))
print("Testing  set score for SVM: %f" % gnb.score(X_test_scaled2  , y_test2 ))

gnb.score

[[59 51 20]
 [21 89  0]
 [33 41 46]]


              precision    recall  f1-score   support

    negative       0.52      0.45      0.49       130
     neutral       0.49      0.81      0.61       110
    positive       0.70      0.38      0.49       120

    accuracy                           0.54       360
   macro avg       0.57      0.55      0.53       360
weighted avg       0.57      0.54      0.53       360

Training set score for SVM: 0.429594
Testing  set score for SVM: 0.425000


<bound method ClassifierMixin.score of GaussianNB(priors=None, var_smoothing=1e-09)>

In [96]:
# bernoulli
from sklearn.naive_bayes import BernoulliNB
#>>> clf = BernoulliNB()
gnb =   BernoulliNB()
Y_pred = gnb.fit(X_train2, y_train2).predict(X_test2)

print(confusion_matrix(y_test2,Y_pred))
print("\n")
print(classification_report(y_test2,Y_pred))

print("Training set score for BNB: %f" % gnb.score(X_train_scaled2 , y_train2))
print("Testing  set score for BNB: %f" % gnb.score(X_test_scaled2  , y_test2 ))

gnb.score

[[83 23 24]
 [31 70  9]
 [41 19 60]]


              precision    recall  f1-score   support

    negative       0.54      0.64      0.58       130
     neutral       0.62      0.64      0.63       110
    positive       0.65      0.50      0.56       120

    accuracy                           0.59       360
   macro avg       0.60      0.59      0.59       360
weighted avg       0.60      0.59      0.59       360

Training set score for BNB: 0.710024
Testing  set score for BNB: 0.583333


<bound method ClassifierMixin.score of BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)>

# Multinomial (with count vectorizer!)

In [105]:
from sklearn.feature_extraction.text import CountVectorizer
fr
TrainData = pd.read_csv('/content/drive/My Drive/Topic detection/ProcessedTrainData3DB.csv', index_col = 0).dropna()

In [108]:
from sklearn.naive_bayes import MultinomialNB

In [109]:
def multinomial(TrainData = TrainData):

    TrainList = TrainData['Processed Text'].tolist()
    vectorizer = CountVectorizer()
    X = vectorizer.fit_transform(TrainList)
    a = X.toarray()
    X = vectorizer.fit_transform(TrainList)
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            val = 'feat' + str(j)
            TrainData[val] = a[i][j]

    X_train2, X_test2, y_train2, y_test2 = train_test_split( TrainData.drop(['Text', 'Sentiment', 'Processed Text'], axis = 1),
    TrainData['Sentiment'], test_size=0.3, random_state=42)

    from sklearn import preprocessing
    encoder = preprocessing.LabelEncoder()

    # encoding train labels 
    encoder.fit(y_train2)
    Y_train2 = encoder.transform(y_train2)

    encoder = preprocessing.LabelEncoder()

    # encoding y_test2 labels 
    encoder.fit(y_test2)
    Y_test2 = encoder.transform(y_test2)

    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    X_train_scaled2 = scaler.fit_transform(X_train2)

    scaler = StandardScaler()
    X_test_scaled2 = scaler.fit_transform(X_test2)


    clf = MultinomialNB()
    Y_pred = clf.fit(X_train2, y_train2).predict(X_test2)
    Y_pred = gnb.fit(X_train2, y_train2).predict(X_test2)
    print(confusion_matrix(y_test2,Y_pred))
    print("\n")
    print(classification_report(y_test2,Y_pred))

    print("Training set score for BNB: %f" % gnb.score(X_train_scaled2 , y_train2))
    print("Testing  set score for BNB: %f" % gnb.score(X_test_scaled2  , y_test2 ))
    return(accuracy_score(Y_pred ,y_test2))
from sklearn.feature_extraction.text import CountVectorizer

In [110]:
multinomial()

[[130   0   0]
 [110   0   0]
 [120   0   0]]


              precision    recall  f1-score   support

    negative       0.36      1.00      0.53       130
     neutral       0.00      0.00      0.00       110
    positive       0.00      0.00      0.00       120

    accuracy                           0.36       360
   macro avg       0.12      0.33      0.18       360
weighted avg       0.13      0.36      0.19       360



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Training set score for BNB: 0.363962
Testing  set score for BNB: 0.361111


0.3611111111111111

# Here I start working on the reddit Data, trying to create a dataset that by end we compiled with the sentiment, to achieve better precision in the model well trained!


In [ ]:
import pandas as pd
reddit = pd.read_csv('/content/drive/My Drive/Topic detection/NewComments_Data1.csv', index_col = 0)

In [ ]:
togo = reddit.copy()

In [ ]:
togo.head()

Submission ID  ...       DATE
Author                       ...           
Lord_TheJc           f7txjb  ...  22-2-2020
EMOSCAMBIO           f7txjb  ...  22-2-2020
drstins_n            f7txjb  ...  22-2-2020
IceTea666            f7txjb  ...  22-2-2020
panoramegamix        f7txjb  ...  22-2-2020

[5 rows x 10 columns]

In [ ]:
len(togo['Text'].tolist())
this = togo['Text'].tolist()

In [ ]:
my_data = pd.DataFrame(this, columns = ['Text'])

In [ ]:
my_data.head()

Text
0  Chiudo il thread, andate su quello nuovo\n\n/r...
1  >Ore 19.30 - Il presunto «paziente 0» negativo...
2  > Si allontana da Codogno e torna ad Avellino:...
3  Dogana slovenia/croazia. Il poliziotto croato ...
4  ho dato una veloce occhiata sui social \n\nNor...

In [ ]:
my_data.shape

(23024, 1)

In [ ]:
my_data.drop(my_data.tail(22400).index, inplace = True) #df.drop(df.tail(n).index,inplace=True)

In [ ]:
my_data.shape

(624, 1)

In [ ]:
data_to_analyze = my_data.copy()
data_to_analyze['Sentimenttobedeleted'] = np.nan
data_to_analyze['Sentiment'] = 'a'
data_to_analyze.head()

Text  ...  Sentiment
0  Chiudo il thread, andate su quello nuovo\n\n/r...  ...          a
1  >Ore 19.30 - Il presunto «paziente 0» negativo...  ...          a
2  > Si allontana da Codogno e torna ad Avellino:...  ...          a
3  Dogana slovenia/croazia. Il poliziotto croato ...  ...          a
4  ho dato una veloce occhiata sui social \n\nNor...  ...          a

[5 rows x 3 columns]

In [ ]:
data_to_analyze.iloc[:, 1]

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
619   NaN
620   NaN
621   NaN
622   NaN
623   NaN
Name: Sentimenttobedeleted, Length: 624, dtype: float64

In [ ]:
import numpy as np
idx_first_empty_row = data_to_analyze.index[np.isnan(data_to_analyze.iloc[:, 1])]
idx_first_empty_row[0]

0

In [ ]:
data_to_analyze.to_csv('/content/drive/My Drive/Topic detection/AMANOREDDIT.csv')

In [ ]:
data_to_analyze = pd.read_csv('/content/drive/My Drive/Topic detection/AMANOREDDIT.csv', index_col = 0)
data_to_analyze.head()

Text  ...  Sentiment
0  Chiudo il thread, andate su quello nuovo\n\n/r...  ...          a
1  >Ore 19.30 - Il presunto «paziente 0» negativo...  ...          a
2  > Si allontana da Codogno e torna ad Avellino:...  ...          a
3  Dogana slovenia/croazia. Il poliziotto croato ...  ...          a
4  ho dato una veloce occhiata sui social \n\nNor...  ...          a

[5 rows x 3 columns]

# Creation TrainData code to share with my teammates :)


In [ ]:
import pandas as pd
import numpy as np



data_to_analyze = pd.read_csv('/content/drive/My Drive/Topic detection/AMANOREDDIT.csv', index_col = 0)
idx_first_empty_row = data_to_analyze.index[np.isnan(data_to_analyze.iloc[:, 1])]
it = idx_first_empty_row[0]


def filler(my_data):
  for index, row in my_data.iterrows():
      if index < it:
        pass
      else:
        print(row['Text'])
        sent = input('   sentiment:\n     ')
        print(sent)
        if sent == 'EXIT':
          my_data.to_csv('/content/drive/My Drive/Topic detection/AMANOREDDIT.csv')
          return
        else:
        #  print(my_data.loc['Sentiment', index ])
         # my_data.loc['Sentiment', index ]= sent
          print(index)
          my_data.at[index, 'Sentimenttobedeleted'	] = 1
          my_data.at[index, 'Sentiment'	] = sent
         # my_data.set_value( index, 'Sentiment', sent)
          print(my_data.head())
          
  return 


filler(data_to_analyze)

In [ ]:
filler(data_to_analyze)

In [ ]:
data_to_analyze = pd.read_csv('/content/drive/My Drive/Topic detection/AMANOREDDIT.csv', index_col = 0)
data_to_analyze.head()

Text  ...  Sentiment
0  Chiudo il thread, andate su quello nuovo\n\n/r...  ...    neutral
1  >Ore 19.30 - Il presunto «paziente 0» negativo...  ...          a
2  > Si allontana da Codogno e torna ad Avellino:...  ...          a
3  Dogana slovenia/croazia. Il poliziotto croato ...  ...          a
4  ho dato una veloce occhiata sui social \n\nNor...  ...          a

[5 rows x 3 columns]